# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linters:
    name: Linting and static analysis
    runs-on: ubuntu-22.04
    timeout-minutes: 5  # usually 1-2, rarely 3 mins (because of installations)
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      - run: pip install -r requirements.txt
      - run: pre-commit install && pip install --upgrade pre-commit && pre-commit install-hooks
      - run: pre-commit run --all-files
